<?php
/**
 * Constants for Qithub CLI client (PHP)
 */

// CONSTANT (ABC順)

// Below is defined by `echo_hr` function
// const HR = '-------------';


const CMD_QUIT = 'q;';
const CR = "\r";
const CU = "\33[1A";
const DEFAULT_WIDTH_SCREEN = 70;
const DIR_SEP     = DIRECTORY_SEPARATOR;
const DO_NOT_ECHO = true;
const INDENT      = '    ';
const NAME_APP    = 'Qithub Client';
const NAME_BOT    = '@qithub';
const NAME_FILE_OPTION = 'option.json';
const NO  = false;
const PATH_DIR_CURRENT = '.';
const VER_APP = '20180418';
const YES     = true;

const PATH_FILE_OPTION = PATH_DIR_CURRENT . DIR_SEP . NAME_FILE_OPTION;
const TITLE_APP = NAME_APP . INDENT . '(Ver.' . VER_APP . ')';

